### ISSUE TITLE
Error in repos[["CRAN"]]  : subscript out of bounds

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/BiocManager#17]
As reported by @kasperdanielhansen:

`BiocManager` should give a descriptive error message

```r
BiocManager::install(version = "devel")
Error in repos[["CRAN"]] : subscript out of bounds
```
This can be fixed by setting a `CRAN` mirror via `chooseCRANmirror()`.

**Comment by kasperdanielhansen** [comment]
Some more investigations: it seems I get this because I have something like
```
options(repos = "http://cran.cnr.Berkeley.edu")
```
in my `.Rprofile.  Instead I need something like
```
options(repos = c("CRAN" = "http://cran.cnr.Berkeley.edu"))
```

**Comment by mtmorgan** [comment]
I don't think the code should depend on a particular name for this repository -- the user gets the Bioconductor repository, plus repositories they have specified. Names should not be important.

**Comment by LiNk-NY** [comment]
@mtmorgan With regards to the comment, my feeling is that if it's important enough,
it should be documented at least internally. 
I can create a page with `@keywords internal`. It won't show up on the package index but
it will be available for reference in the package.

**Comment by LiNk-NY** [comment]
How's this for code that doesn't use the names? 

```diff
-    if (cran == "@CRAN@" || grepl(snapshot_pattern, cran))
-        repos[["CRAN"]] <- "https://cran.rstudio.com"
+    creps <- "@CRAN@" %in% repos | grepl(snapshot_pattern, repos)
+    repos[creps] <- "https://cran.rstudio.com"
```

**Comment by LiNk-NY** [comment]
See comparison https://github.com/Bioconductor/BiocManager/compare/557efd8270887cefe0e23d2cb0c98ddbbf64a00c...repos

**Comment by mtmorgan** [comment]
I think it would help (me, at least) to have unit tests that illustrate current successes and current failures. I realize you're fixing a bug in code from BiocInstaller, but the repositories can really be named anything, and can point anywhere. Also, the `"@CRAN@" %in% repos` always returns a vector of length 1 (i.e., the length of the left-hand side of `%in%`) which is not what you want?

**Comment by LiNk-NY** [comment]
I've added a unit test for the `.repositories_base` function based on the example described above. I've also corrected the mistake with the `|` condition. Thanks.

**Comment by mtmorgan** [comment]
I made some commits to the branch

```
5e4384e use withr::with_options() for fail-safe option
88f8ee4 minor formatting
7d04801 restore original comment, separate code functions
7a3be24 revise unit tests
30c7c57 edge case unit tests and bug fix
c570a02 remove unused documentation file
```
Some commentary --

5e4384e if `test_that` were function calls I would have used `op = options(...); on.exit(options(op))` so that options would never leak outside the test, but that's not available for test_that. Instead, I used withr, which is already imported by testthat so available during testing

7d04801 I think the formal documentation of the function rather than a nested comment is a good thing to do, but I want my packages to be clean and the documentation available to the user to be user-oriented rather than developer notes. So there is probably a roxygen strategy that does this or minimizes the exposure to the user of this level of documentation, but this bug fix is not the place to explore that. I also restored the original code because it made it clear that there were _two_ things that the function is doing -- avoiding use of mran when appropriate, and replacing @CRAN@.

7a3be24 I revised the unit test in several ways. First it seemed important to capture the original bug. Then it seemed important to capture the original behavior, which made me look at the original code. In particular, I don't think that an mran repository not labelled 'CRAN' should be updated; there could be reasons why one might include a CRAN and mran repository. This invalidates the unit tests that expected `CRAN1=...` to be updated. I then added possible edge cases, including a zero-length repository and an unnamed "@CRAN@", which actually pointed to a bug in the code and hence fix. I don't think the 'test multiple things in one test' (e.g., creating a `repos` with several test cases) is such a good strategy, even if it saves some typing, because it makes it harder to see what exactly is being tested. My own tests in this case are probably not extensive enough when it comes to making sure that repos of length > 1 are handled correctly. 

One feature that I thought of was to make sure that the updated repositories were `unique()`, but I wasn't sure how to handle duplicate repositories but with different names. At any rate that would be a new feature rather than a bug fix.
