### ISSUE TITLE
remove 00LOCK-* files when interrupted

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/BiocManager#19]
Thanks to @LTLA for reporting this. 

Issue:
When interrupting `BiocManager::install` with <kbd>Ctrl</kbd> + <kbd>C</kbd>, `00LOCK-*` folders are not removed.

**Comment by hpages** [comment]
Just to clarify, this is an `install.packages()` "feature". The 00LOCK-* leftover files after CTRL+C or other premature interruption of the installation process have been an annoyance for years... It might not be easy to come up with a proper fix though since only the process that created the 00LOCK file should be allowed to remove it (otherwise all kinds of bad things could happen in the multiple-user/multiple-R-session context).

**Comment by LiNk-NY** [comment]
I guess we can just identify leftover `00LOCK-*` folders and warn the user.

**Comment by hpages** [comment]
The fundamental problem is that there is no easy way in general to distinguish between a leftover `00LOCK-*` folder and an _active_ one (i.e. one that belongs to another process and that is still being used by that process). You could use an heuristic e.g. see how old is the `00LOCK-*` folder (the older, the more likely it is to be a leftover) and maybe other criteria but these things are never easy to test and they need to work on all platforms. I guess you could just warn the user before you start installing if the library directory contains `00LOCK-*` folders, without trying to distinguish between leftovers and _active_ ones. In this case there would be a (small) risk of false positive when some of the `00LOCK-*` folders  are _active_ folders but at least it's safe because you actually don't try to remove anything ;-) However the question is whether this warning is useful to the user. Isn't it too late? Maybe it should be an error? That would mean that `BiocManager::install()` refuses to install anything as long as there are `00LOCK-*` folders at sight. But that would also mean that 2 users wouldn't be able to concurrently install 2 different packages on a system with a shared R anymore :-/

This is a tricky topic and there are probably good reasons why `install.packages()` isn't trying to do any of this. You might benefit from bringing this topic to R-devel or directly to R-core via our infiltrated agent ;-) If there is a good solution, there is no reason why it wouldn't belong in `install.packages()` instead of `BiocManager::install()`.

**Comment by LTLA** [comment]
This all sounds sensible, though I felt that I wasn't getting this issue with interruptions of `biocLite()`... I don't really remember, though, so I can't be sure.

**Comment by natti-cyber** [comment]
How do you remove OOLOCK

**Comment by LiNk-NY** [comment]
Hi Natasha, @natti-cyber 
You can remove it by simply deleting the folder from your files.
