### ISSUE TITLE
BiocVersion and .version_map

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/BiocManager#22]
Martin, @mtmorgan, Valerie @vobencha raised an important question about
having different ways of ensuring the right Bioconductor version. What are the
pros of having `BiocVersion` over solely using the `.version_map`? 

One pro is that `BiocVersion` persists across sessions without having to
depend on an internet connection and querying the online resource at
every load up (which takes time). 

It also becomes more portable since `BiocVersion` is installed with the
rest of the Bioc packages.

What are your thoughts?

**Comment by mtmorgan** [comment]
BiocVersion should be an 'implementation detail'; if there are problems with BiocManager::version(), then these should be addressed.

**Comment by vobencha** [comment]
This came up during one of the infrastructure meetings. I asked Marcel some questions I had when updating the BBS code to use BiocManager and making the new release schedule.

BiocManager 'Suggests' BiocVersion and the approach is to get the version from BiocVersion if installed, otherwise get it from https://bioconductor.org/config.yaml. This assumes the 2 will always be in sync and give the same information. If that's true I wasn't sure why we needed them both. Maybe the idea was convenience when the user was off-line and config.yaml was not available but BiocVersion was?

BiocVersion was created before we had BiocManager; BiocManager only has a soft dependency on BiocVersion. This arrangement made me wonder if there were plans for eventually deprecating BiocVersion.

I guess my question comes down to why not either get version information from BiocVersion with a stronger dependency (Imports or Depends vs Suggests) or get it from the config.yaml?

Sorry if this was explained before and I missed it.

**Comment by mtmorgan** [comment]
BiocVersion was created in conjunction with BiocManager, and is not a candidate for deprecation.

Whatever config.yaml says, the version that the user has installed is the version consistent with BiocVersion, e.g., on my current R-3.5 installation there is no way to know from config.yaml whether I intend to use the release or devel version of Bioconductor.

The 'Suggests:' relationship is necessary to install BiocManager from CRAN -- in a brand new installation of BiocManager, we don't know which branch of the Bioconductor repository to retrieve BiocVersion from -- we can't install it until after we've installed BiocManager, and BiocManager has consulted config.yaml for the right 'user' version.

**Comment by vobencha** [comment]
Thanks for the details.
