### ISSUE TITLE
BiocManager does not give useful suggestion when R version is incongruent

### ISSUE THREAD

**Issue by Alanocallaghan** [Bioconductor/BiocManager#50]
Upgrading between R and BioConductor versions obviously produces an invalid version. However, currently BiocManager doesn't suggest anything useful, only suggests the install page below, which itself doesn't mention how to handle it, at best a vignette does. In fact, the "update" section seems to suggest that running `install()` will update packages/version, when it doesn't.

```r
BiocManager::install()
# error: Bioconductor version '3.7' requires R version '3.5'; see https://bioconductor.org/install
```

I would suggest either adding a suggestion to the error message, or changing the install help page on the Bioc site to mention differing R versions, and to solve by (eg) `install(version="x.y")`

**Comment by LiNk-NY** [comment]
Alan @Alanocallaghan,
I'm not sure I am understanding the root of the issue you're posting here. 
The error message here says that you need at least R version `3.5` to install
Bioconductor using `BiocManager`. 

For older R versions (`< 3.5.0`), you'd have to install Bioconductor using
the legacy method which is listed at the bottom of the page:
https://bioconductor.org/install/#Legacy

`BiocManager::install` only works on the packages **given** that you have
the appropriate R version.

**Comment by Alanocallaghan** [comment]
The message states that one must use exactly R-3.5, not at least R-3.5. I was running R 3.5. I then updated to 3.6. My existing Bioconductor installation was then broken (ie, I could not install nor update any packages using `BiocManager::install()` (the error message is the one I posted). Setting `BiocManager::install(update=TRUE)` lead to the same error message. Running `BiocManager::install(version="3.9")` fixed it, though there was no information to let me know that anywhere that I could see.

This issue isn't documented anywhere on `https://bioconductor.org/install` nor in `?install`. What I'm saying is it would be good to write somewhere on one or both "If you have updated your version of R, you may need to run `BiocManager::install(version="x.y")` to have a compatible/working version of Bioconductor".

**Comment by Alanocallaghan** [comment]
Something like the PR I submitted :) Hope that's clear now, apologies I wrote the issue in a rather tired rush.

**Comment by LiNk-NY** [comment]
It's still hard to say what the root of the issue is since you didn't provide `sessionInfo` but my guess is that you had a stale version of `BiocVersion` that was pointing to Bioc `3.7`.
It's always recommended to use a new folder in (see `.libPaths()`) for installing a newer version of Bioconductor so that you don't have version clashes that lead to errors such as these. 
The other solution that would've worked is to do:
```
remove.packages("BiocVersion")
BiocManager::install()
```
See https://support.bioconductor.org/p/122277/

We'll look into making this transition from versions more intuitive. 

- Marcel

**Comment by andrewrech** [comment]
Marcel,

I have the same issue here as @Alanocallaghan. It would be nice if there was a clean upgrade path for stale components of the Bioconductor packages. I think some confusion here pushes users to just install off Github.

Thanks

Andrew

**Comment by LiNk-NY** [comment]
The current design of `BiocManager` precludes the installation of an alternate Bioconductor version without explicit instruction from the user. Therefore, running `BiocManager::install()` will not upgrade the Bioconductor version because Bioc version `3.7` was already installed. That is why using the argument `version = '3.9'` worked. 

I'm working to make the error message more helpful when loading a stale `BiocVersion` version (after an R version upgrade for example).

@andrewrech It's difficult to have a 'clean upgrade path' when switching R versions **and** re-using existing packages. This is why we recommend using a clean folder for installation when switching to a new Bioconductor version. We can also look into making this port, e.g. from `3.7` to `3.9`, easier by possibly providing a function that installs all packages used in `3.7` to a Bioc version `3.9` folder

One alternate possibility is to use:
```
BiocManager::install(version = "3.9", checkBuilt = TRUE, ask = FALSE)
```
Which will upgrade and re-install all packages available in your current `.libPaths` which may not always be the potential solution..

Best regards,
Marcel

**Comment by Alanocallaghan** [comment]
I get the difficulty - I choose not to have alternate libpaths because it ends up wasting disk space, incongruent packages, etc. Just suggesting that for those of us too stubborn to follow the guidelines, the error message/suggested web page/`install()` help page mentions the problem

**Comment by andrewrech** [comment]
Thanks Marcel for the helpful response; I better understand the issue.

Indeed, upgrading everything in my `.libPaths` won't work.

I think since base R can be upgraded without re-installing packages, and Bioconductor is made up of R packages, most users might expect that Bioconductor can also be upgraded without re-installing packages.

Thanks for your hard work on this open source project and for responding to these comments.
