### ISSUE TITLE
Support for older versions of R

### ISSUE THREAD

**Issue by jimhester** [Bioconductor/BiocManager#8]
I realize this will probably be a wontfix, but it would be great of BiocManager would work for R versions >= 3.1. In the tidyverse we support our packages back to R 3.1, so if I want to use BiocManager in devtools (I do!) I will need to have fallback code to BiocInstaller for older versions.

If BiocManager was compatible with these versions as well I could just depend on it rather than needing the fallback.

The yaml has the R -> Bioc mappings for much further back, so I think it should be technically possible at least...

**Comment by LiNk-NY** [comment]
Hi Jim, 
Yes, I see the desire for making `BiocManager` compatible with old and future versions. 
Making it backwards compatible would entail creating `BiocVersion` packages for the previous releases and adding them in the respective "releases" or some workaround. 
I will discuss this with Martin @mtmorgan. Thanks!

**Comment by mtmorgan** [comment]
I guess @jimhester is looking only for install() support. I think we would do something like .version_choose_best() and if it were < 3.7 call `source("...biocLite.R"); biocLite(...)` with args from `install()`. For 'us' to do this we would then have to decide whether to support the args to install(), to biocLite(), or both. And since users would see that `install()` works, they might expect the other functionality to be available too. It doesn't sound very <del>tidy</del> clean, and an appeal of BiocManager was to get rid of a decade of legacy support...

**Comment by jimhester** [comment]
Actually the only thing I need is `BiocManager::repositories()`; but I have worked around it as-is if it will be troublesome to provide.

**Comment by mtmorgan** [comment]
ok we'll follow your prior and wontfix!
