### ISSUE TITLE
Outdated dependencies lead to error upon installation: Package 'xxx' is not available for this version of R

### ISSUE THREAD

**Issue by matdoering** [Bioconductor/BiocManager#83]
I just got a report from a user of my Bioconductor package openPrimeR. He tried to install the package in R version 4.02 with BiocManager 3.12. So he called

`BiocManager::install(c("openPrimerR")) `

which resulted in `Package 'openPrimeR' is not available for this version of R`. Since the package is actually available for this version of R, I was quite confused when I received the report. So I tried to reproduce the problem on my machine and I received the same output. However, after updating my installed BioC packages via `BiocManager::install()`, the problem went away and I could install openPrimeR with BiocManager without any problems.

So, the problem appears to be that BiocManager reports that a package is unavailable when the packages it depends on are outdated. Since this appears to this misleading error message (package not available), it would be great if you could find a way to fix the problem. In my opinion, BiocManager should update all of the dependencies and then install the package itself, shouldn't it?

**Comment by hpages** [comment]
Agreed that it seems more logical to do things in the opposite order: first update existing packages, then install requested packages.

**Comment by hpages** [comment]
Even though in your case @matdoering, I get that error too:
```
> BiocManager::install("openPrimerR")
Bioconductor version 3.12 (BiocManager 1.30.10), R 4.0.2 Patched (2020-06-24
  r78746)
Installing package(s) 'openPrimerR'
Warning message:
package ‘openPrimerR’ is not available (for R version 4.0.2 Patched) 
```
Maybe it's because the name of your package is **openPrimeR**, not **openPrimerR** ?

**Comment by mtmorgan** [comment]
I don't think the diagnosis 'BiocManager reports that a package is unavailable when the packages it depends on are outdated' is correct. Instead I think the user asked for a combination of R / Bioc that doesn't exist, e.g., because when they updated to R 4.0.* they continued to use the library, and hence BiocVersion, for R 3.6.*. I'm also guessing they were on Windows, where the path to the binary is of the form `http://bioconductor.org/packages/<Bioc Version>/bioc/bin/windows/contrib/<R major version>/<pkg>.zip`.

I have difficulty emulating this, though, and get an informative error message

```
> BiocManager::install("openPrimeR")
Error: Bioconductor version '3.10' requires R version '3.6'; see
  https://bioconductor.org/install
```
when trying, e.g., to use Bioc version 3.10 with R version 3.6. In the pre-release version of BiocManager (install from Bioconductor/BiocManager) I get a little more guidance
```
> BiocManager::install("openPrimeR")
Error: Bioconductor version '3.10' requires R version '3.6'; use
  `BiocManager::install(version = '3.12')` with R version 4.0; see
  https://bioconductor.org/install
```

But I'm not really sure where the underlying problem in the original report is, because there is not enough information to reproduce the problem.

**Comment by matdoering** [comment]
@hpages The name `openPrimeR` is correct, so this is not the problem. It would be nice though if it were so simple :-)

Maybe it is also a package-specific problem and not a problem with BiocManager. In this case, I wouldn't know how to diagnose this though...

@mtmorgan The user had R 4.02 with the current BiocManager installed. I don't know about his OS. On my machine I had the same setup, using Linux. I also received the same error message as the user. So, I would assume to reproduce the problem, you could use this procedure:

- Select a package (e.g. openPrimeR)
- Install the package from a previous BioC version (including all of its dependencies)
- Execute: BiocManager::install(openPrimeR) using the newest BioC version

I don't have the time to investigate this further, so it would be nice if you could try to create a reproducible example.

In any way, it would be reasonable to check which paths lead BiocManager to proclaim that a package is not available for a specific version of R, even though it is available.

**Comment by mtmorgan** [comment]
So far the only way to reproducibly produce the report is the one Hervé points out in your post https://github.com/Bioconductor/BiocManager/issues/83#issue-743040230, where you used the incorrect spelling of your package in `BiocManager::install()`.

If the package were spelt correctly, then on Linux, where R version is not important, it would have been found and installation would have been tried. Maybe there was an installation error or warning that you are not reporting here? Sometimes users report the final message about installation failure without noticing earlier problems reported during installation.

I tried a second time to reproduce this following your recipe: within R-4.0.3, installing the bioc 3.11 version of your package (and dependencies) and then forcing installation of the 3.12 version. The installation was successful, so I am still not able to reproduce your problem.

`BiocManager::install()` mostly delegates to `install.packages(repos=BiocManager::repositories())` so that packages are installed from the correct location. I'm reluctant to do anything more complicated, especially without a reproducible problem.

**Comment by Jiefei-Wang** [comment]
JFYI, I'm on Windows and the error can be reproduced with the devel R. Not sure if this is related.

```
Bioconductor version 3.13 (BiocManager 1.30.10), R Under development (unstable) (2020-09-03
  r79126)
Installing package(s) 'openPrimerR'
Warning message:
package ‘openPrimerR’ is not available (for R Under development)
```

**Comment by mtmorgan** [comment]
Ok, if I have R version 3.6.3 and try to install from the 3.12 repos I get the warning
```
> R.version.string
[1] "R version 3.6.3 Patched (2020-02-29 r77906)"
> install.packages("openPrimeR", repos = "https://bioconductor.org/packages/3.12/bioc")
Installing package into ‘/Users/ma38727/Library/R/3.6/Bioc/3.10/library’
(as ‘lib’ is unspecified)
Warning message:
package ‘openPrimeR’ is not available (for R version 3.6.3 Patched)
```
but that's because the 3.12 version of the package has
```
Depends:
    R (>= 4.0.0)
```
So there's a second way to produce the  warning, but this does really jibe with the original report (using R-4.0.2)

I didn't see the query about how Bioconductor version is determined -- it is determined by the version of a package BiocVersion; see the 'how it works' section of the BiocManager vignette https://github.com/Bioconductor/BiocManager/blob/master/vignettes/BiocManager.Rmd#L275

**Comment by Jiefei-Wang** [comment]
I do not think the outdated package is the cause of the error either. I first upgrade my packages to Bioc 3.12. Then I download the source of `IRanges` and change its version number to `1.25.2`, which does not fit the version requirement according to the description of `openPrimeR`. After installing it, I try to install `openPrimeR`
```
> packageVersion("IRanges")
[1] ‘1.25.2’
> BiocManager::install("openPrimeR",version = "3.12")
Bioconductor version 3.12 (BiocManager 1.30.10), R 4.0.2 (2020-06-22)
Installing package(s) 'openPrimeR'
also installing the dependency ‘IRanges’
```
It looks like `BiocManager` is smart enough to detect outdated packages. It will install its dependencies if it has to do so. The problem is something else.

Cheers,
Jiefei

**Comment by LiNk-NY** [comment]
It looks like it was user error. Without a proper report there is not much we can do. Thanks.
