### ISSUE TITLE
Determine exact version number of devel?

### ISSUE THREAD

**Issue by bbimber** [Bioconductor/BiocManager#90]
Hello,

Does BiocManager have any function to determine the version number of the current 'devel' branch, not just the version you have installed? Something like BioManager::getCurrentDevelopVersion()? 

The package internally has this info, since I can use the private method: 

BiocManager:::.version_bioc("devel")

If nothing else, some method like this might be useful if you'd consider exporting it:

isDevel <- function() {
    .version_bioc("devel") == version()
}

**Comment by LiNk-NY** [comment]
Hi @bbimber 
We are staying away from "devel" version tags and using version numbers
because the "devel" version is different across releases though the
function you highlight here references the version map.

What is the use case for having an `isDevel` function? 

The devel version is not an 'advertised' version and we prefer users to use
the release version of Bioconductor and `BiocManager::version()` to
determine their version number.
Developers and bleeding-edge users have to consciously opt in to the
devel version by following the steps shown in the Advanced use section
of the BiocManager vignette in which case `BiocManager::version()`
should suffice. 

Best, 
Marcel

**Comment by bbimber** [comment]
Sure, but you support BioManager::install(version = 'devel'), dont you?

The use case is related to testing on github actions. We run our module against bioc release and devel. It is convenient to have this coded as the strings ('devel'), not a specific release. this way we dont need to keep changing that. From here, our CI code installs BiocManager/Bioconductor, and then installs our package. It's been a challenge getting all the potential interacting code to understand the correct Bioc version. Currently, I set this in RProfile (matrix.config.bioc is our bioc version):

BiocManager::install(version = "${{ matrix.config.bioc }}", ask = FALSE);
cat(append = TRUE, file = "~/.Rprofile", "options(repos = BiocManager::repositories());")

# this is for remotes:
cat(append = TRUE, file = "~/.Rprofile", "Sys.setenv(R_BIOC_VERSION=BiocManager::version());");
if (BiocManager::version() == BiocManager:::.version_bioc('devel')) {cat(append = TRUE, file = "~/.Rprofile", "options(Bioc_git_branch = 'master');") }

When I originally posted this, I was looking for a way for R code to figure out if the currently installed Bioc version was in fact the latest development version. That's b/c is this is true, I need to set the bioc git branch to make remotes operate properly. 

After I wrote this question, I did figure out that since I have this value in ${{ matrix.config.bioc }}, I dont need a purely R solution. However, I maintain it would be useful for R code to be able to query BiocManager and determine if the currently installed version is in fact the latest release or whether it's the latest development version. My proposed implementation might be sub-optimal and there might be a better mechanism to figure this out.

**Comment by LiNk-NY** [comment]
Yes, we do use "devel" out of convenience but prefer a tangible `3.13` version. 

For GitHub Actions, I personally recommend one `.github/workflows/*.yml` file in each of the `RELEASE_3_12` and `main` branches rather than one `yml` for both branches for simplicity and to avoid over-engineering. 
Devel versions of a package are constantly changing and it's a good idea to keep those continually tested. Not so much
for release versions. These are meant to be stable. They should be tested when a bug fix is introduced otherwise
I recommend to keep an eye out on the `3.12` build report. 

Leo has done some work towards setting up GHA for Bioconductor packages and you might find the `biocthis::use_bioc_github_action` useful. 

Best,
Marcel

**Comment by bbimber** [comment]
@LiNk-NY thanks for the replies. I appreciate the suggestion, but maintaining different versions of the config across branches is really the opposite of what one should be doing. There really should be some context-based scheme that propagates all the way through. I will grant that my example above involves setting far too many parameters, which suggests either I'm doing something wrong or the configuration scheme is suboptimal. Nonetheless, there really should be a reasonable way to toggle this without maintaining different versions of a file.

I'll also grant that the problem I'm facing is primarily related to how remotes interacts with Bioconductor, not BiocManager per se.

For our particular modules, we depend on various Bioconductor modules, but our module is not a bioconductor module. We expect to depend on stable functions in those bioconductor modules. Running our module against both bioc-release and bioc-devel has been really useful to proactively identify problems or changed APIs. 

The remotes developers replied to my question on this, so I'm going to pursue this over there.

**Comment by LiNk-NY** [comment]
This is the most straightforward way in Bioconductor since you are technically maintaining both release
and devel versions. These two versions can even diverge with the introduction of bug fix commits.

I would recommend the use of the Bioconductor containers which will release you from the
management of versions and parameters where `BiocManager::version()` will provide you
with the appropriate response.
